### ISSUE TITLE
Read from primary

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-healthcheck#13]
We have found there is some lag between mongo syncs and how fast the application works. As a work around, add an optional time delay.

eg. .../test?delay=1

**Comment by jewzaam** [comment]
https://jewzaam.gitbooks.io/lightblue-specifications/content/language_specification/execution.html

```
{
   ...
   "execution": {
      "readPreference": "primary"
   }
}
```

**Comment by dcrissman** [comment]
Looks like this is being handled in https://github.com/lightblue-platform/lightblue-client/pull/297

**Comment by paterczm** [comment]
#297 is merged. It can be added to the healthcheck now.
