### ISSUE TITLE
Change response from health check

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-healthcheck#3]
Right now it's very basic.  You get a pass or fail.  It's also something specific to the health check.  How about using the lightblue response object and putting the reason for failure in as an error code and message?  Then, even if we don't use it in automated scripts a human could easily tell what is failing when the test is run.  Right now you would have no idea.

**Comment by jewzaam** [comment]
@dcrissman I think this is pretty important.  I'm running the health check in dev today and I get back the status is error.  But, requests to lightblue work so I have no idea what is wrong.

**Comment by dcrissman** [comment]
@jewzaam FWIW the full exception and stack trace is logged in the server.log

**Comment by jewzaam** [comment]
Maybe not put a full stack in the response, but it would be useful to say
in an error what caused it to fail.
