### ISSUE TITLE
On success, a delete for all test entries with hostname should be performed

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-healthcheck#9]
This will help prevent orphan rows.

Counter argument... this would prevent multiple tests from running on the same node concurrently.

**Comment by dcrissman** [comment]
@jewzaam @paterczm - Is there a desire for multiple tests to run at the same time?

**Comment by jewzaam** [comment]
It should be supported.  Ideally I'd recommend a TTL index to kill old
records.  Without that, you could delete anything where uid matches or it
is older than some period of time, say 5 min.

**Comment by jewzaam** [comment]
Oh, successful run will delete where uid is equal, correct?  This is just
at the end do a cleanup.  Then I'd say > 5min old..
